baseURL = "http://www.wangzhao.me/"
languageCode = "en-us"
title = "Wang Zhao's blog"

defaultContentLanguage = "zh-cn"
publishdir = "public"

disqusShortname = "www-wangzhao-me"
googleAnalytics = "UA-114388506-1"

[permalinks]
	post = "/:year/:month/:slug/"

[[menu.main]]
	weight = 1
	identifier = "home"
	name = "Home"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
	url = "/"
[[menu.main]]
	weight = 2
	identifier = "categories"
	name = "Categories"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
	url = "/categories"
[[menu.main]]
	weight = 3
	identifier = "tags"
	name = "Tags"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
	url = "/tags"
[[menu.main]]
	weight = 4
	identifier = "archives"
	name = "Archives"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
	url = "/archives"
[[menu.main]]
	weight = 5
	identifier = "about"
	name = "About"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
	url = "/#about"

[[menu.links]]
	weight = 1
	identifier = "github"
	name = "Github"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
	url = "https://github.com/nero19960329"
[[menu.links]]
	weight = 2
	identifier = "weibo"
	name = "Weibo"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-weibo\"></i>"
	url = "https://weibo.com/5064242931/profile"

[[menu.misc]]
	weight = 1
	identifier = "rss"
	name = "RSS"
	pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
	url = "/index.xml"

[params.header.rightLink]
	class = "open-algolia-search"
	icon = "search"
	url = "/#search"


[author]
	name = "Wang Zhao"
	bio = "Student @ Tsinghua University"
	job = "Student @ Tsinghua University"
	location = "Beijing"
	picture = "https://s1.ax1x.com/2018/02/25/9dmmKU.jpg"

[params]
	clearReading = true

	dateFormat = "2006年1月2日"

	sidebarBehavior = 1
	coverImage = "villa-daylight-blur.jpg"
	thumbnailImage = true
	thumbnailImagePosition = "left"
	autoThumbnailImage = true
	imageGallery = true
	hierarchicalCategories = true
	syntaxHighlighter = 'highlight.js'
	favicon = "img/favicon.png"

	[[params.sharingOptions]]
		name = "Facebook"
		icon = "fa-facebook-official"
		url = "https://www.facebook.com/sharer/sharer.php?u=%s"

	[[params.sharingOptions]]
		name = "Twitter"
		icon = "fa-twitter"
		url = "https://twitter.com/intent/tweet?text=%s"

	[[params.sharingOptions]]
		name = "Google+"
		icon = "fa-google-plus"
		url = "https://plus.google.com/share?url=%s"

[taxonomies]
	tag = "tags"
	category = "categories"
	archive = "archives"